name: Node.js CI

on:
  push:
    branches: [ "firstApiCommit" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # you can adjust versions if needed

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies (uses package-lock.json if present)
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run Jest tests
        run: npm test
